version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ptitnotebook_db
      - POSTGRES_USER=nozoe
      - POSTGRES_PASSWORD=sekiren_secret
    ports:
      - "5432:5432"

  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  chroma_data: